sudo: required
dist: trusty
language: python
python: 3.4
os: linux
compiler: gcc
addons:
    apt:
        packages:
            - libboost-test-dev
            - libhdf5-serial-dev
            - libopenmpi-dev
            - libfftw3-dev
            - libgsl0-dev
            - gfortran
            - python3-numpy
            - python3-matplotlib
            - python3-scipy
            - python3-h5py
            - python3-jsonpickle
virtualenv:
    system_site_packages: true

install:
    - pip install -r requirements.txt
    - ./prepare_travis.sh
script: nosetests
